Repository dasch-swiss/dsp-docs, pull requests merged in 2020-05, with the labels that each got.

#17 Update documentation using the name DSP-UI
  README.md
  docs/assets/images/dsp-ui/admin-image1.png
  docs/assets/images/dsp-ui/admin-image2.png
  docs/assets/images/dsp-ui/expert-search.png
  docs/assets/images/dsp-ui/extended-search.png
  docs/assets/images/dsp-ui/fulltext-search-simple.png
  docs/assets/images/dsp-ui/fulltext-search-with-project-filter.png
  docs/assets/images/dsp-ui/loader-after-submit-status.png
  docs/assets/images/dsp-ui/loader-before-submit-status.png
  docs/assets/images/dsp-ui/loader-submitting-status.png
  docs/assets/images/dsp-ui/login-form.png
  docs/assets/images/dsp-ui/message-error.png
  docs/assets/images/dsp-ui/message-short.png
  docs/assets/images/dsp-ui/search-panel.png
  docs/assets/images/dsp-ui/search-results-filter.png
  docs/assets/images/dsp-ui/search-results-simple.png
  docs/assets/images/dsp-ui/submit-form-data-loader.png
  docs/developers/dsp-ui/contribution/index.md
  docs/developers/dsp-ui/documentation/action/admin-image.md
  docs/developers/dsp-ui/documentation/action/existing-name.md
  docs/developers/dsp-ui/documentation/action/index-action.md
  docs/developers/dsp-ui/documentation/action/key.md
  docs/developers/dsp-ui/documentation/action/message.md
  docs/developers/dsp-ui/documentation/action/progress-indicator.md
  docs/developers/dsp-ui/documentation/action/sort-button.md
  docs/developers/dsp-ui/documentation/action/stringify-string-literal.md
  docs/developers/dsp-ui/documentation/action/truncate.md
  docs/developers/dsp-ui/documentation/core/index-core.md
  docs/developers/dsp-ui/documentation/index.md
  docs/developers/dsp-ui/documentation/search/expert-search.md
  docs/developers/dsp-ui/documentation/search/extended-search.md
  docs/developers/dsp-ui/documentation/search/fulltext-search.md
  docs/developers/dsp-ui/documentation/search/index-search.md
  docs/developers/dsp-ui/documentation/search/search-panel.md
  docs/developers/dsp-ui/documentation/viewer/index-viewer.md
  docs/developers/dsp-ui/documentation/viewer/search-results.md
  docs/developers/knora-ui/contribution/index.md
  docs/developers/knora-ui/documentation/action/index-action.md
  docs/developers/knora-ui/documentation/core/index-core.md
  docs/developers/knora-ui/documentation/index-authentication.md
  docs/developers/knora-ui/documentation/index.md
  docs/developers/knora-ui/documentation/viewer/index-viewer.md
  docs/developers/knora/documentation/index.md
  docs/index.md
  mkdocs.yml
  requirements.txt
Labels: documentation, refactor

#18 Add Makefile command to README.md
  README.md
Labels: documentation, enhancement

#21 Update docs.dasch.swiss/community
  docs/community/about-us.md
  docs/community/product-updates.md
  docs/index.md
  docs/user-guide/index.md
Labels: documentation
